def testValue = 3

pipeline {
    agent any
    stages {
        stage ("Greatings"){
            steps{
                echo "Hello World!"
                sh "exit 0"
            }
        }
    }
}