library identifier: 'my-shared-libraries@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/carlosrodlop/my-pipeline-home.git',
   credentialsId: 'carlosrodlop-GH'])

def configYaml = """---
k8_agent_yaml : 'maven_kaniko_pod.yaml'
gh_cred : 'GHE-carlosrodlop'
gh_repo : 'https://github.beescloud.com/support-team/simple-app.git'
gh_branch : 'develop'
dockerfile_path : 'src/main/docker/Dockerfile'
docker_registry : 'supportbeescloud'
"""

mavenK8Project(configYaml)